### ISSUE TITLE
Admin: case 'select_plugins' causes debug error

### ISSUE THREAD

**Issue by torvista** [AndrewBerezin/zen-cart-sitemap-xml#2]
```
 $plugin = (isset($_POST['plugin']) ? $_POST['plugin'] : '');
      $active_plugins = $plugin;
      $sql = "UPDATE " . TABLE_CONFIGURATION . " SET configuration_value='" . zen_db_input($active_plugins) . "' where configuration_key='SITEMAPXML_PLUGINS'";
```

$plugins is an array or '' so needs to be exploded if an array. Otherwise causes a debug error.
Suggest:
`$active_plugins = (is_array($plugin) ? implode(';', $_POST['plugin']) : '');`

**Comment by AndrewBerezin** [comment]
Yes, my bug. Mindlessly copied recoding lines without checking :(
