### ISSUE TITLE
alert css overrides default message stack css in 1.55d

### ISSUE THREAD

**Issue by torvista** [AndrewBerezin/zen-cart-sitemap-xml#3]
Hi, 
the red-bold alert overrides the css used for the message stack as per the image.
![untitled-1](https://cloud.githubusercontent.com/assets/4391026/23233186/558510bc-f94e-11e6-9cd8-bfece27cbe93.gif)
regards
Steve

**Comment by AndrewBerezin** [comment]
Thanks! Fixed.
